version: '3'

services:
  db:
    image: mysql:latest
    container_name: db_c
    ports: 
      - "3306:3306"
    networks:
      - net
    env_file:
      - .env    # Ruta del archivo
    volumes:
      - ../sql-data-services-appMardac/db:/var/lib/mysql
      - .:/usr/src/app
  api:
    image: node:latest
    container_name: app_api
    build: .
    ports:
      - "5000:3000"
    depends_on:
      - db
    networks:
      - net
    links:
      - db
    env_file:
      - .env    # Ruta del archivo
networks:
  net:

