name: pipeline_ci

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  ci_to_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm ci
      - run: npm test
      - run: npm build 