name: pipeline_ci

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  ci_to_dev:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:latest
        ports: 
          - "3306:3306"
        volumes:
          - ./sql-data-services-appMardac/db:/var/lib/mysql
          - .:/usr/src/app
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm ci
      - run: npm test
      - run: npm build 